version: "3.7"
services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    ports:
      - 4180:4180
    environment:
      - OAUTH2_PROXY_COOKIE_SECRET=<random 32 byte string>
      - OAUTH2_PROXY_PROVIDER=azure
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_AZURE_TENANT=<Azure AD teenant>
      - OAUTH2_PROXY_CLIENT_ID=<Azure App-Client-ID>
      - OAUTH2_PROXY_CLIENT_SECRET=<Azure App-Client-Secret-value>
      - OAUTH2_PROXY_OIDC_ISSUER_URL=https://login.microsoftonline.com/<your teenant>/v2.0
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_HTTP_ADDRESS=http://0.0.0.0:4180
      - OAUTH2_PROXY_REDIRECT_URL=https://app.domain.com/oauth2/callback
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
      - OAUTH2_PROXY_COOKIE_NAME=SESSION
      - OAUTH2_PROXY_COOKIE_SAMESITE=lax
      - OAUTH2_PROXY_SESSION_STORE_TYPE=redis
      - OAUTH2_PROXY_REDIS_CONNECTION_URL=redis://redis
      - OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER=true
      - OAUTH2_PROXY_PASS_USER_HEADERS=true
      - OAUTH2_PROXY_COOKIE_DOMAIN=*
      - OAUTH2_PROXY_COOKIE-SECURE=true
      # For some reason Azure does not respond with an email, so this is a workaround:
      - OAUTH2_PROXY_OIDC_EMAIL_CLAIM=sub
