# main.yml
# Workflow that build server, client and Docker and publish to Docker Hub and Github Package Registry
name: Build and publish

on:
  push:
    branches:
      - main
      - develop
    tags:
      - '*'
  pull_request:
    branches:
      - main
      - develop
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run:
          yarn
      - name: Build
        run: |
          yarn build:server
          yarn build:client          
  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
        -
          name: Checkout
          uses: actions/checkout@v3
        -
          name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        -
          name: Build and push
          uses: docker/build-push-action@v3
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/webrtc-player-portal:latest


